/** Shared visible UI copy for actions, statuses, sections, and common field labels. */
export const uiCopy = {
  actions: {
    addScenario: "Add scenario",
    reloadFile: "Reload file",
    syncFile: "Sync file",
    openFolder: "Open folder",
    showInFolder: "Show in folder",
    copyPath: "Copy path",
    copyResponse: "Copy response",
    sendOnce: "Send once",
    revert: "Revert",
    closeTab: "Close tab",
    closeOtherTabs: "Close other tabs",
    closeAllTabs: "Close all tabs",
    cancel: "Cancel",
    save: "Save",
    saveDraft: "Save draft",
    delete: "Delete",
    close: "Close",
    insertBlock: "Insert block",
    technicalDetails: "Technical details",
    copyId: "Copy page ID",
    buildAll: "Build all",
    checkFiles: "Check files",
    openSite: "Open site",
    resetWidth: "Reset width",
  },
  status: {
    active: "Active",
    inactive: "Inactive",
    running: "Running",
    stopped: "Stopped",
    unmatched: "Unmatched",
    unsaved: "Unsaved",
  },
  sections: {
    server: "Server",
    scenario: "Scenario",
    matchers: "Matchers",
    response: "Response",
    requests: "Requests",
  },
  fields: {
    host: "Host",
    port: "Port",
    path: "Path",
    statusCode: "Status code",
    priority: "Priority",
    delayMs: "Delay (ms)",
    intervalMs: "Interval (ms)",
    loopCount: "Loop count",
  },
  helper: {
    zeroMeansUnlimited: "0 means unlimited",
  },
} as const;
