export const PAYLOAD_DOCUMENT_MAX_DOCUMENTS = 64;
export const PAYLOAD_DOCUMENT_MAX_CHARS = 96_000_000;
export const PAYLOAD_DOCUMENT_MAX_DECODED_DOCUMENTS = 3;
export const PAYLOAD_DOCUMENT_DEFAULT_SEARCH_LIMIT = 2_000;
export const PAYLOAD_DOCUMENT_PREVIEW_CHARS = 4_096;
export const PAYLOAD_DOCUMENT_INITIAL_VIEWPORT_LINES = 384;
export const PAYLOAD_DOCUMENT_LARGE_LIVE_THRESHOLD_CHARS = 250_000;
export const PAYLOAD_DOCUMENT_LARGE_LIVE_MIN_HYDRATION_INTERVAL_MS = 2_000;
export const PAYLOAD_DOCUMENT_PAGE_SIZE = 256;
export const PAYLOAD_DOCUMENT_MAX_PAGES_PER_REQUEST = 2;
export const PAYLOAD_DOCUMENT_PREFETCH_BEFORE_LINES = 256;
export const PAYLOAD_DOCUMENT_PREFETCH_AFTER_LINES = 512;
export const PAYLOAD_DOCUMENT_MAX_CACHED_VIEWPORT_LINES = 2_304;

export function payloadDocumentPreview(rawText: string, maxChars = PAYLOAD_DOCUMENT_PREVIEW_CHARS): string {
  return rawText.length <= maxChars ? rawText : rawText.slice(0, maxChars);
}
