import { isPlainRecord } from "../../shared/json-utils";

/**
 * Stringifies a JSON-compatible value into a small YAML subset used by the scenario editor.
 */
export function stringifySimpleYaml(value: unknown, indent = 0): string {
  const pad = " ".repeat(indent);
  if (Array.isArray(value)) {
    if (value.length === 0) return `${pad}[]\n`;
    return value
      .map((item) => {
        if (isYamlScalar(item)) return `${pad}- ${formatYamlScalar(item)}\n`;
        return `${pad}-\n${stringifySimpleYaml(item, indent + 2)}`;
      })
      .join("");
  }
  if (isPlainRecord(value)) {
    const entries = Object.entries(value).filter(([, item]) => item !== undefined);
    if (entries.length === 0) return `${pad}{}\n`;
    return entries
      .map(([key, item]) => {
        if (isYamlScalar(item)) return `${pad}${key}: ${formatYamlScalar(item)}\n`;
        return `${pad}${key}:\n${stringifySimpleYaml(item, indent + 2)}`;
      })
      .join("");
  }
  return `${pad}${formatYamlScalar(value)}\n`;
}

/**
 * Parses the YAML subset generated by stringifySimpleYaml, including arrays and nested maps.
 */
export function parseSimpleYaml(text: string): unknown {
  const lines = text
    .split(/\r?\n/)
    .map((raw) => ({ indent: raw.match(/^ */)?.[0].length ?? 0, text: raw.trim() }))
    .filter((line) => line.text && !line.text.startsWith("#"));
  if (lines.length === 0) return {};
  const [value] = parseYamlBlock(lines, 0, lines[0].indent);
  return value;
}

type SimpleYamlLine = { indent: number; text: string };

/**
 * Recursive descent parser for the scenario editor YAML subset.
 */
export function parseYamlBlock(lines: SimpleYamlLine[], startIndex: number, indent: number): [unknown, number] {
  const current = lines[startIndex];
  if (!current || current.indent < indent) return [{}, startIndex];
  if (current.text.startsWith("-")) return parseYamlArray(lines, startIndex, indent);
  return parseYamlObject(lines, startIndex, indent);
}

/**
 * Parses YAML list items at a given indentation level.
 */
export function parseYamlArray(lines: SimpleYamlLine[], startIndex: number, indent: number): [unknown[], number] {
  const output: unknown[] = [];
  let index = startIndex;
  while (index < lines.length && lines[index].indent === indent && lines[index].text.startsWith("-")) {
    const rest = lines[index].text.slice(1).trim();
    index += 1;
    if (!rest) {
      const [child, nextIndex] = parseYamlBlock(lines, index, indent + 2);
      output.push(child);
      index = nextIndex;
      continue;
    }
    if (looksLikeYamlKeyValue(rest)) {
      const item: Record<string, unknown> = {};
      index = parseYamlKeyValueInto(rest, item, lines, index, indent + 2);
      if (index < lines.length && lines[index].indent >= indent + 2) {
        const [child, nextIndex] = parseYamlBlock(lines, index, indent + 2);
        if (isPlainRecord(child)) Object.assign(item, child);
        index = nextIndex;
      }
      output.push(item);
    } else {
      output.push(parseYamlScalar(rest));
    }
  }
  return [output, index];
}

/**
 * Parses YAML object keys at a given indentation level.
 */
export function parseYamlObject(
  lines: SimpleYamlLine[],
  startIndex: number,
  indent: number,
): [Record<string, unknown>, number] {
  const output: Record<string, unknown> = {};
  let index = startIndex;
  while (index < lines.length && lines[index].indent === indent && !lines[index].text.startsWith("-")) {
    index = parseYamlKeyValueInto(lines[index].text, output, lines, index + 1, indent + 2);
  }
  return [output, index];
}

/**
 * Parses one YAML key-value line, optionally consuming its nested child block.
 */
export function parseYamlKeyValueInto(
  text: string,
  output: Record<string, unknown>,
  lines: SimpleYamlLine[],
  nextIndex: number,
  childIndent: number,
) {
  const colon = text.indexOf(":");
  if (colon < 0) throw new Error(`Expected key: value, got ${text}`);
  const key = text
    .slice(0, colon)
    .trim()
    .replace(/^['"]|['"]$/g, "");
  const rawValue = text.slice(colon + 1).trim();
  if (!rawValue) {
    if (nextIndex < lines.length && lines[nextIndex].indent >= childIndent) {
      const [child, next] = parseYamlBlock(lines, nextIndex, lines[nextIndex].indent);
      output[key] = child;
      return next;
    }
    output[key] = {};
    return nextIndex;
  }
  output[key] = parseYamlScalar(rawValue);
  return nextIndex;
}

/**
 * Checks whether an inline YAML item looks like key: value.
 */
export function looksLikeYamlKeyValue(text: string) {
  const colon = text.indexOf(":");
  return colon > 0 && /^[A-Za-z0-9_.-]+\s*:/.test(text);
}

/**
 * Parses a scalar YAML value, including inline JSON for objects and arrays.
 */
export function parseYamlScalar(text: string): unknown {
  const trimmed = text.trim();
  if (trimmed === "null" || trimmed === "~") return null;
  if (trimmed === "true") return true;
  if (trimmed === "false") return false;
  if (trimmed === "{}") return {};
  if (trimmed === "[]") return [];
  if ((trimmed.startsWith("{") && trimmed.endsWith("}")) || (trimmed.startsWith("[") && trimmed.endsWith("]"))) {
    return JSON.parse(trimmed);
  }
  if ((trimmed.startsWith('"') && trimmed.endsWith('"')) || (trimmed.startsWith("'") && trimmed.endsWith("'"))) {
    return trimmed.slice(1, -1).replace(/\\"/g, '"').replace(/\\n/g, "\n");
  }
  const numeric = Number(trimmed);
  if (Number.isFinite(numeric) && /^-?\d+(\.\d+)?$/.test(trimmed)) return numeric;
  return trimmed;
}

/**
 * Checks whether a value can be rendered on one YAML line.
 */
export function isYamlScalar(value: unknown) {
  return value === null || ["string", "number", "boolean"].includes(typeof value);
}

/**
 * Formats a scalar YAML value safely.
 */
export function formatYamlScalar(value: unknown) {
  if (value === null) return "null";
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  const text = String(value ?? "");
  if (!text || /[:#\n\r\t{}[\],&*?|-]|^\s|\s$/.test(text)) return JSON.stringify(text);
  return text;
}
